// backend/db/setup-local-env.ts - Print environment variable examples
console.log('🔧 FuelSync Hub Environment Variables');
console.log('');
console.log('Copy and paste these export commands to set up your environment:');
console.log('');
console.log('# Database Configuration');
console.log('export DB_HOST=localhost');
console.log('export DB_PORT=5432');
console.log('export DB_NAME=fuelsync_dev');
console.log('export DB_USER=postgres');
console.log('export DB_PASSWORD=postgres');
console.log('export DB_SSL=false');
console.log('');
console.log('# Server Configuration');
console.log('export PORT=3001');
console.log('export NODE_ENV=development');
console.log('');
console.log('# JWT Configuration');
console.log('export JWT_SECRET=your-jwt-secret-key-change-this-in-production');
console.log('export JWT_EXPIRES_IN=24h');
console.log('export JWT_AUDIENCE=fuelsync-tenant-api');
console.log('export JWT_ISSUER=fuelsync-auth');
console.log('');
console.log('# Admin JWT Configuration');
console.log('export ADMIN_JWT_SECRET=your-admin-jwt-secret-key-change-this-in-production');
console.log('export ADMIN_JWT_EXPIRES_IN=12h');
console.log('export ADMIN_JWT_AUDIENCE=fuelsync-admin-api');
console.log('export ADMIN_JWT_ISSUER=fuelsync-admin-auth');
console.log('');
console.log('For Windows (PowerShell):');
console.log('Replace "export" with "$env:" (e.g., $env:DB_HOST="localhost")');
console.log('');
console.log('For Windows (CMD):');
console.log('Replace "export" with "set" (e.g., set DB_HOST=localhost)');